//Airship Upgrade Action Types
export const ADD_AIRSHIP_UPGRADE = "ADD_AIRSHIP_UPGRADE";
export const SET_AIRSHIP_UPGRADE = "SET_AIRSHIP_UPGRADE";
export const AIRSHIP_UPGRADES_LOADING = "AIRSHIP_UPGRADES_LOADING";

// Auth Action Types
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const USERS_LOADED = "USERS_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const USER_LOADING = "USER_LOADING";
export const USERS_LOADING = "USERS_LOADING";

// Character Action Types
export const ADD_CHARACTER = "ADD_CHARACTER";
export const SET_CHARACTERS = "SET_CHARACTERS";
export const REMOVE_CHARACTER = "REMOVE_CHARACTER";
export const UPDATE_CHARACTER = "UPDATE_CHARACTER";
export const CHARACTERS_LOADING = "CHARACTERS_LOADING";

// Downtime Action Types
export const SET_DOWNTIME = "SET_DOWNTIME";
export const ADD_DOWNTIME = "ADD_DOWNTIME";
export const DOWNTIME_LOADING = "DOWNTIME_LOADING";
export const REMOVE_DOWNTIME = "REMOVE_DOWNTIME";

// Downtime Jobs Action Types
export const SET_DOWNTIME_JOBS = "SET_DOWNTIME_JOBS";
export const DOWNTIME_JOBS_LOADING = "DOWNTIME_JOBS_LOADING";

// Downtime Types Action Types
export const SET_DOWNTIME_TYPES = "SET_DOWNTIME_TYPES";
export const DOWNTIME_TYPES_LOADING = "DOWNTIME_TYPES_LOADING";

// Items Action Types
export const SET_ITEMS = "SET_ITEMS";
export const EDIT_ITEM = "EDIT_ITEM";
export const ITEMS_LOADING = "ITEMS_LOADING";

//Items Owned Action Types
export const SET_ITEMS_OWNED = "SET_ITEMS_OWNED";
export const ADD_ITEMS_OWNED = "ADD_ITEMS_OWNED";
export const ITEMS_OWNED_LOADING = "ITEMS_OWNED_LOADING";
export const UPDATE_ITEM_OWNED = 'UPDATE_ITEM_OWNED';
export const REMOVE_ITEM_OWNED = "REMOVE_ITEM_OWNED";

// Mission Action Types
export const ADD_MISSION = "ADD_MISSION";
export const SET_MISSIONS = "SET_MISSIONS";
export const REMOVE_MISSION = "REMOVE_MISSION";
export const UPDATE_MISSION = "UPDATE_MISSION";
export const MISSIONS_LOADING = "MISSIONS_LOADING";

// PCSubclass Action Types
export const SET_PCSUBCLASSES = "SET_PCSUBCLASSES";
export const ADD_PCSUBCLASS = "ADD_PCSUBCLASS";
export const PCSUBCLASSES_LOADING = "PCSUBCLASSES_LOADING";

// Races Action Types
export const SET_RACES = "SET_RACES";
export const RACES_LOADING = "RACES_LOADING";

// Subclass Action Types
export const SET_SUBCLASSES = "SET_SUBCLASSES";
export const SUBCLASSES_LOADING = "SUBCLASSES_LOADING";

// Transaction Action Types
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";

