# Generated by Django 3.0.2 on 2020-07-02 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('dateCreated', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('maxHp', models.IntegerField(blank=True, null=True)),
                ('armorClass', models.IntegerField(blank=True, null=True)),
                ('passivePerception', models.IntegerField(blank=True, null=True)),
                ('altVision', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSubClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(choices=[('Fighter', 'Fighter'), ('Cleric', 'Cleric'), ('Wizard', 'Wizard'), ('Bard', 'Bard'), ('Druid', 'Druid'), ('Barbarian', 'Barbarian')], max_length=255)),
                ('subclassName', models.CharField(max_length=255)),
                ('subclassLevel', models.IntegerField()),
                ('isClass', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('costGold', models.IntegerField()),
                ('costSilver', models.IntegerField()),
                ('costCopper', models.IntegerField()),
                ('description', models.TextField()),
                ('numberInSkymall', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('playedOn', models.DateField(blank=True, default=datetime.date.today)),
                ('visable', models.BooleanField(default=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='missions', to='characters.Character')),
                ('dm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmed', to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goldPcs', models.IntegerField()),
                ('silverPcs', models.IntegerField()),
                ('copperPcs', models.IntegerField()),
                ('airshipPot', models.BooleanField(default=True)),
                ('earnedSpent', models.IntegerField(choices=[(-1, 'Spent'), (1, 'Earned')])),
                ('characters', models.ManyToManyField(related_name='transactions', to='characters.Character')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='characters.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCharacter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcClasses', to='characters.Character')),
                ('playerClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.CharacterSubClass')),
            ],
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('downtimeType', models.CharField(choices=[('TR', 'Training Room'), ('MC', 'Miscellaneous')], max_length=2)),
                ('numOfDaysSpent', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimeSpend', to='characters.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='raceName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.CharacterRace'),
        ),
    ]
