# Generated by Django 3.0.2 on 2020-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dead',
            field=models.BooleanField(default=False),
        ),
    ]
