# Generated by Django 3.0.2 on 2020-07-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_dead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owningCharacter', to='characters.Character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='characters.Item')),
            ],
        ),
    ]
