# Generated by Django 3.0.2 on 2020-07-06 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_itemsowned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='playedOn',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
