# Generated by Django 3.0.2 on 2020-07-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20200706_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='playedOn',
            field=models.DateField(),
        ),
    ]
