# Generated by Django 3.0.2 on 2020-07-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20200706_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='playedOn',
            field=models.DateField(blank=True),
        ),
    ]
