# Generated by Django 3.0.2 on 2020-07-06 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20200706_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='playedOn',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
