# Generated by Django 3.0.2 on 2020-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_auto_20200706_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='altVision',
            field=models.CharField(choices=[('60DV', '60 ft Dark Vision'), ('NORM', 'Normal Vision')], default='NORM', max_length=4),
        ),
        migrations.AlterField(
            model_name='mission',
            name='playedOn',
            field=models.DateField(default='2020-06-06'),
            preserve_default=False,
        ),
    ]
