# Generated by Django 3.0.8 on 2020-07-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20200706_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='episode',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='charactersubclass',
            name='className',
            field=models.CharField(choices=[('Fighter', 'Fighter'), ('Cleric', 'Cleric'), ('Wizard', 'Wizard'), ('Bard', 'Bard'), ('Druid', 'Druid'), ('Barbarian', 'Barbarian'), ('Druid', 'Druid'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Artificer', 'Artificer'), ('Blood Hunter', 'Blood Hunter')], max_length=255),
        ),
    ]
