# Generated by Django 3.0.8 on 2020-07-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_auto_20200720_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercharacterclass',
            old_name='date',
            new_name='dateCreated',
        ),
    ]
