# Generated by Django 3.0.8 on 2020-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20200720_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allPcsCanPurchase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='canBePurchasesBy',
            field=models.ManyToManyField(blank=True, null=True, related_name='itemPurchasedBy', to='characters.Character'),
        ),
        migrations.AddField(
            model_name='item',
            name='downtimeCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='costCopper',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='costGold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='costSilver',
            field=models.IntegerField(default=0),
        ),
    ]
