# Generated by Django 3.0.8 on 2020-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_auto_20200722_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='canBePurchasesBy',
            field=models.ManyToManyField(blank=True, related_name='itemPurchasedBy', to='characters.Character'),
        ),
    ]
