# Generated by Django 3.0.8 on 2020-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20200722_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='typeOfItem',
            field=models.CharField(choices=[('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Gear', 'Gear'), ('Magic', 'Magic')], default='Gear', max_length=6),
        ),
    ]
