# Generated by Django 3.0.8 on 2020-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0018_auto_20200730_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='typeOfItem',
            field=models.CharField(choices=[('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Gear', 'Gear'), ('Magic', 'Magic'), ('Component', 'Component')], default='Gear', max_length=10),
        ),
    ]
