# Generated by Django 3.0.8 on 2020-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0020_itemsowned_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dateOfDeath',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='startingCheckmarks',
            field=models.IntegerField(default=0),
        ),
    ]
