# Generated by Django 3.0.8 on 2020-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0021_auto_20200731_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='dateOfDeath',
            field=models.DateField(blank=True, null=True),
        ),
    ]
