# Generated by Django 3.0.8 on 2020-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0022_auto_20200731_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='character',
            old_name='firstName',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='downtime',
            name='downtimeType',
            field=models.CharField(max_length=255),
        ),
    ]
