# Generated by Django 3.0.8 on 2020-08-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0023_auto_20200802_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downtime',
            name='downtimeType',
        ),
    ]
