# Generated by Django 3.0.8 on 2020-08-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0024_remove_downtime_downtimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='downtimeType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimeTransaction', to='characters.DowntimeType'),
        ),
    ]
