# Generated by Django 3.0.8 on 2020-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0025_downtime_downtimetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chosenClass', models.CharField(choices=[('Fighter', 'Fighter'), ('Cleric', 'Cleric'), ('Wizard', 'Wizard'), ('Bard', 'Bard'), ('Druid', 'Druid'), ('Barbarian', 'Barbarian'), ('Druid', 'Druid'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Artificer', 'Artificer'), ('Blood Hunter', 'Blood Hunter')], max_length=255)),
                ('validUntil', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
