# Generated by Django 3.0.8 on 2020-08-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0026_downtimejobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='description',
            field=models.TextField(),
        ),
    ]
