# Generated by Django 3.0.8 on 2020-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0027_auto_20200806_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimetype',
            name='description',
            field=models.TextField(),
        ),
    ]
