# Generated by Django 3.0.8 on 2020-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0028_auto_20200806_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirshipUpgrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgradeType', models.CharField(choices=[("Madam Lysalka's Tavern", "Madam Lysalka's Tavern"), ("Carlyle's Trading Network", "Carlyle's Trading Network"), ('The Blacksmith', 'The Blacksmith'), ('The Alchemist', 'The Alchemist'), ('The Master of Arms', 'The Master of Arms'), ('The Researcher', 'The Researcher')], max_length=255)),
                ('fromAirshipPot', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
