# Generated by Django 3.0.8 on 2020-08-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0029_airshipupgrades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='canBePurchasesBy',
            new_name='canBePurchasedBy',
        ),
    ]
