# Generated by Django 3.0.8 on 2020-08-14 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0031_auto_20200812_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airshipupgrades',
            name='creationDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='creationDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='itemsowned',
            name='dateLastModified',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creationDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
