# Generated by Django 3.1 on 2020-08-19 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0032_auto_20200814_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
