# Generated by Django 3.1 on 2020-08-20 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0034_downtime_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='airshipUpgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_airship_upgrade', to='characters.airshipupgrades'),
        ),
        migrations.AddField(
            model_name='downtime',
            name='downtimeGoldTransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_gold_transaction', to='characters.transaction'),
        ),
    ]
