# Generated by Django 3.1 on 2020-08-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0035_auto_20200820_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downtime',
            name='airshipUpgrade',
        ),
        migrations.RemoveField(
            model_name='downtime',
            name='downtimeGoldTransaction',
        ),
        migrations.AddField(
            model_name='airshipupgrades',
            name='airshipUpgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_airship_upgrade', to='characters.downtime'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='downtimeGoldTransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtime_gold_transaction', to='characters.downtime'),
        ),
    ]
