# Generated by Django 3.1 on 2020-08-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0036_auto_20200820_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airshipupgrades',
            old_name='airshipUpgrade',
            new_name='downtimeAirshipUpgrade',
        ),
    ]
