# Generated by Django 3.1 on 2020-08-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0037_auto_20200820_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
