# Generated by Django 3.1 on 2020-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0038_transaction_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
